### ISSUE TITLE
是否可以修改下载路径

### ISSUE THREAD

**Issue by lbwleon** [yangshun1029/aria2gui#10]
如题

**Comment by YangDejie** [comment]
+1

**Comment by yangshun1029** [comment]
下载最新版1.24
打开~/Library/Application Support/com.Aria2GUI/sh/startaria.sh
修改$HOME/Downloads/，需要是绝对路径

如果是1.23之前的版本打开/Applications/Aria2GUI.app/Contents/Resources/startaria.sh进行修改

**Comment by MeiJiaYun** [comment]
你好，补充一下，修改的位置为   /Users/用户名/Library/Application\ Support/com.Aria2GUI/sh/startaria.sh       ，将 用户名  换做你自己的用户名，同时感谢  yangshun1029作者给我们带来好用的软件。

**Comment by mildnes** [comment]
你好，补充一下，OS X EI 10.16下，没有找到动态生成的startaria.sh。。
因为需要修改`force-save=true`这个参数。
请教一下，需要再哪里找到startaria.sh这个文件呢。

**Comment by yangshun1029** [comment]
@mildnes 设置里面，有个编辑配置文件，修改后保存，重启应用即可，如果加了force-save=true这个参数有个问题，如果删除了已经下载的任务，重新打开应用后都会重新自动下载，所以慎重加这个参数。

**Comment by mildnes** [comment]
@yangshun1029  感谢，最后解决了这个问题了，通过软件定位到了startaria这个文件。我去找下您说的那个文件。
