### ISSUE TITLE
1.4版本造成Mac循环性卡死

### ISSUE THREAD

**Issue by LarryBrin** [yangshun1029/aria2gui#100]
1.4版本要比1.38版本下载速度快，但是每当开始下载，很快就会造成Mac瘫痪卡死，强制关机后再开机仍然会卡死，然后循环。。。。除非不用，现在换回低版本，这个问题就不再出现。

**Comment by keepersay** [comment]
我也遇到了，换回低版本出现Internal server error，只能使用1.4版本然后把并发调小，我目前是100*100，同时下3个

**Comment by wangbingqian** [comment]
我也是，换回1.38没再复现

**Comment by yangshun1029** [comment]
@LarryBrin 说明硬件以及系统版本，调小线程数是否有用

**Comment by keepersay** [comment]
@yangshun1029 macbookpro13 2014年中，10.13.2调小进程数有用

**Comment by huahuizi** [comment]
我也遇到这个问题了，一直以为是系统的问题，重新装了个系统，哎啥也不说了@LarryBrin，这个问题怎么解决啊

**Comment by LarryBrin** [comment]
@yangshun1029 嗯，有用

**Comment by yangshun1029** [comment]
@huahuizi 不好意思，下个版本会调整初始线程数，会保留256的最大值

**Comment by huahuizi** [comment]
@yangshun1029  近期会放出来新的版本吗？

**Comment by alanzhangzm** [comment]
@yangshun1029 想请问一个无关的问题。一个相同的aria2配置文件，使用你的aria2c可以下载pt，但使用aria2官方release的aria2c文件就会被pt识别为非法的客户端。所以想请问下你编译aria2c时用了什么参数？

**Comment by alanzhangzm** [comment]
@yangshun1029 想请问一个无关的问题。一个相同的aria2配置文件，使用你的aria2c可以下载pt，但使用aria2官方release的aria2c文件就会被pt识别为非法的客户端。所以想请问下你编译aria2c时用了什么参数？

**Comment by kukusyaoran** [comment]
256 线程太高了，机械硬盘直接卡死，下载路径换到 SSD 才能正常下载。

**Comment by lonecloud** [comment]
同电脑直接卡死

**Comment by wander1** [comment]
昨天刚升系统，以为是系统的问题，哈哈哈哈原来是Aria的新版本问题

**Comment by EroyalBoy** [comment]
今天抹光了数据再重装了
