### ISSUE TITLE
百度云添加任务后立即被删除无法下载

### ISSUE THREAD

**Issue by shanenoluna** [yangshun1029/aria2gui#101]
OS系统：10.11.6 (15G31)
Aria2GUI：1.4.0
Aria2：1.33.1
百度网盘exporter：1.0.1
问题描述：可以导出，但是导出后不能下载，立即被删除。如图所示。求解救TAT。
![screen shot 2017-12-29 at 6 01 37 pm](https://user-images.githubusercontent.com/34936857/34434679-a9b76820-ecc2-11e7-9f1e-089271c57249.png)
![screen shot 2017-12-29 at 6 05 01 pm](https://user-images.githubusercontent.com/34936857/34434710-dc93dc4c-ecc2-11e7-9985-a13f0f246c40.png)

**Comment by yangshun1029** [comment]
@shanenoluna 用BaiduExporter试试，目前版本是0.9.7，鼠标移到那个X那里会显示错误原因

**Comment by shanenoluna** [comment]
谢谢大神回复我！我这个...不知道怎么回事现在好像好了QAQ，我也不懂编程什么的，好像有重启过一次就好了。。？另外，我发现最新版里面状态栏的下拉菜单里面，"show main view"有个typo，写的是"mian"。恩  你可以之后的新版本改一下！谢谢大神！！

**Comment by yangshun1029** [comment]
@shanenoluna 状态栏模式有点问题，下个版本修复
