### ISSUE TITLE
请问在NAS的docker里的ARIA2如何使用您的配置？

### ISSUE THREAD

**Issue by Dijion** [yangshun1029/aria2gui#102]
好像这个问题有点超过范围了~有闲心就看看哈~

nas里的docker里下的aria2下某盘的文件，总有的文件不好使，下一半就挂了。但是用大神的GUI下载这个文件就一点问题没有，请问如何把docker里的aria2调教成像大神这个版本这么好用~

**Comment by yangshun1029** [comment]
https://github.com/yangshun1029/aria2gui/blob/master/MacGap/aria2.conf
