### ISSUE TITLE
显示 “error name resolution failed”

### ISSUE THREAD

**Issue by RagicXenosWDon** [yangshun1029/aria2gui#103]
用百度网盘助手（版本1.0.2）导出下载不成功，显示错误“error name resolution failed”，并且文件名称第一个字符丢失。

<img width="154" alt="2018-01-10 4 08 40" src="https://user-images.githubusercontent.com/30687073/34761883-97d2cd40-f620-11e7-822f-51da33674228.png">
<img width="1012" alt="2018-01-10 4 08 59" src="https://user-images.githubusercontent.com/30687073/34761884-9bad8388-f620-11e7-8a35-f74325d0305f.png">

**Comment by RagicXenosWDon** [comment]
已尝试过重新卸载安装插件，重新卸载安装 Chrome，重新卸载安装 Aria2GUI，修改网盘文件名称，均没有效果。

**Comment by yangshun1029** [comment]
@RagicXenosWDon 贴出下载地址

**Comment by RagicXenosWDon** [comment]
链接: https://pan.baidu.com/s/1gfU7675 密码: 2sui

**Comment by yangshun1029** [comment]
@RagicXenosWDon  我试了可以正常下载，搜索了下这个问题应该是和DNS有关系，你可以尝试换用其它DNS，比如114之类的
