### ISSUE TITLE
Error: Internal server error

### ISSUE THREAD

**Issue by clay-f** [yangshun1029/aria2gui#107]
Aria2-gui version: 1.4
aria2 version: 1.33.1
OS version: mac os 10.10

百度云登录之后下载导出下载文件，报错提示服务没有打开, 重新安装 aria2、aira2-gui 依然报错

![2018-01-20 12 08 31](https://user-images.githubusercontent.com/16079417/35183286-493901ee-fe1e-11e7-868e-fc7d2f3b0405.png)

![foo](https://user-images.githubusercontent.com/16079417/35183336-3f379088-fe1f-11e7-8353-b5654283a8b0.jpg)

**Comment by liu1169681** [comment]
我也是这个原因 而且出这个提示之后浏览器无法正常打开 无限风火轮 也不能正常关机 只能按关机键才能关  不知道是什么原因  有没有大神知道
