### ISSUE TITLE
无法运行1.4.1

### ISSUE THREAD

**Issue by AshtonCoop** [yangshun1029/aria2gui#108]
下载最新1.4.1版本,打开发现无法运行?
Mac系统: 10.13.3
Macbook Pro 13 touch bar, late 2016

删除重装同样问题

<img width="423" alt="screen shot 2018-01-27 at 9 10 07 pm" src="https://user-images.githubusercontent.com/19743271/35478266-9bf55508-03a6-11e8-97d9-2054626c4a2b.png">

非常感谢!

**Comment by CharlesDY** [comment]
Me too......

**Comment by zczyzi** [comment]
换个解压软件试试，我用Archiver解压出错，用BetterZip成功

**Comment by yangshun1029** [comment]
@AshtonCoop @CharlesDY 重新打包上传了，再试试

**Comment by CharlesDY** [comment]
![image](https://user-images.githubusercontent.com/13417572/35479182-089f4788-042c-11e8-9994-9cfe459c577c.png)
可以用了！

**Comment by AshtonCoop** [comment]
非常感谢!
