### ISSUE TITLE
aria2怎么下bt和解析磁力链接

### ISSUE THREAD

**Issue by EroyalBoy** [yangshun1029/aria2gui#110]
网上一直没找到方法，自己测试一直跑不动

**Comment by iSteveyang** [comment]
Bt有上传种子，从没有发现过问题，磁力链接从没有下载成功过

**Comment by Frankr0** [comment]
磁力链接从没有下载成功过+1
很久之前可以下载 某一时间后就无法下载了

**Comment by iSteveyang** [comment]
@yangshun1029 大佬, [网上有个方法](http://kiligwyu.com/aria2-trackers-auto-update/), 通过shell脚本自动更新aria2.conf文件中的bt-tracker, 我试着改了改,还是失败, 不知您能参考一下吗?

**Comment by 343700931** [comment]
@yangshun1029 iSteveyang 的方法我也试了，不行

**Comment by molvqingtai** [comment]
试了添加 tracker，也没有速度
Aria2 1.33.1

**Comment by octodile** [comment]
貌似能下载，但是不显示速度和完成情况。

**Comment by chenguangcui** [comment]
tracker已经添加 版本：1.34.0 无法下载bt 一级magnet。
