### ISSUE TITLE
Aria2GUI-v1.4.1.zip 下载后无法解压

### ISSUE THREAD

**Issue by Chen-Hu** [yangshun1029/aria2gui#113]
通过 release 页下载的1.4.1版本的压缩包，无法解压。
下载后的sha1sum数值
➜  Downloads shasum Aria2GUI-v1.4.1.zip
8af87b24bd3ec1aa379b48d18f02ceeef013fcfc  Aria2GUI-v1.4.1.zip

用几种下载工具都试了，都无法解压。请检查。

**Comment by yangshun1029** [comment]
@Chen-Hu 系统自带解压软件和The Unarchiver 都可以正常解压
