### ISSUE TITLE
修改配置之后打不开了

### ISSUE THREAD

**Issue by qq253498229** [yangshun1029/aria2gui#114]
忘记了修改什么了，好像是什么打开状态栏什么的，然后窗口就消失了。
kill软件并重启软件后仍然一闪就消失。
请问如何解决？或者如何卸载再次安装？

**Comment by yangshun1029** [comment]
@qq253498229 用AppCleaner（免费）或者CleanMyMac（收费）等卸载软件卸载应用后重新安装
