### ISSUE TITLE
下载速度只有几十K 比限了速的百度盘下载还慢

### ISSUE THREAD

**Issue by aLiu10** [yangshun1029/aria2gui#115]
速度一点都没提升  有人遇到这个问题吗

**Comment by LarryBrin** [comment]
我这边速度还行，昨天还在用，要比迅雷加速通道还要快些

**Comment by iHTCboy** [comment]
@aLiu10 用iPhone的话可以参考我的文章： http://ihtc.cc/2018/02/16/2018-02-16_利用iPhone“破解”下载百度云文件限速问题/
