### ISSUE TITLE
@rpath报错

### ISSUE THREAD

**Issue by allanGold** [yangshun1029/aria2gui#119]
dyld: Library not loaded: @rpath/libclang_rt.asan_osx_dynamic.dylib
  Referenced from: /Users/allan/Library/Developer/Xcode/DerivedData/Aria2GUI-flvcdbmawhkoqohiziztrznsxcql/Build/Products/Debug/Aria2GUI.app/Contents/Frameworks/GitHubUpdates.framework/Versions/A/GitHubUpdates
  Reason: image not found
求解

**Comment by starlightjy** [comment]
@allanGold 我的也出现这样的报错了
dyld: Library not loaded: @rpath/libclang_rt.asan_osx_dynamic.dylib......
GitHubUpdates.framework/Versions/A/GitHubUpdates
你有解决吗?
