### ISSUE TITLE
aria2更新到1.34版本了。

### ISSUE THREAD

**Issue by yolin11** [yangshun1029/aria2gui#122]
如题。

**Comment by yangshun1029** [comment]
https://github.com/aria2/aria2/issues/1198
虽然我编译成功了，但是应该会跳过这个版本，1.3.5放出来我会更新
@yolin11

**Comment by kilvn** [comment]
@yangshun1029 为何下载列表的 1.4.1 下载下来还是 1.33.1 ？？？

**Comment by seth2017** [comment]
OK




------------------ 原始邮件 ------------------
发件人: "Nick"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 下午2:15
收件人: "yangshun1029/aria2gui"<aria2gui@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [yangshun1029/aria2gui] aria2更新到1.34版本了。 (#122)




Closed #122.
