### ISSUE TITLE
macOS, Error: Internal server error

### ISSUE THREAD

**Issue by tommyZZM** [yangshun1029/aria2gui#127]
总是显示这个
==== updated =====
 安装`aria2c`并启动服务之后就没有这个报错了，但似乎仍然不能启动下载

**Comment by jdoiholakn** [comment]
我的也是同样的问题

**Comment by tommyZZM** [comment]
reply @jdoiholakn 安装`aria2c`并启动服务之后就没有这个报错了，但似乎仍然不能启动下载

**Comment by zhanggang807** [comment]
我也是同样的问题，启动后就报Error: Internal server error

**Comment by wikihao** [comment]
同样是这个问题
