### ISSUE TITLE
DMG装载后可以自动打开么？

### ISSUE THREAD

**Issue by wumouse** [yangshun1029/aria2gui#13]
DMG装载后没有自动打开。让我一直以为您的软件不能用。下载了好几个历史版本。尝试了好多次。
这里发一个issue，希望别的人能看见。以免踩坑

**Comment by yangshun1029** [comment]
@wumouse 并没有遇到这个问题，这个issue暂时保留

**Comment by wumouse** [comment]
@yangshun1029 嗯，我是在 OSX El Capitan 10.11.5 下使用的。

**Comment by zhEdward** [comment]
@wumouse  操作系统版本一样，我在 【设置】-【安全与隐私】修改打开app的扩大到【允许任何来源】后，正常打开 app。

**Comment by StraightJet** [comment]
把app拖出用就好了嘛，话说大多数人不会每次去打开dmg来启动app吧。。。
