### ISSUE TITLE
version number broken

### ISSUE THREAD

**Issue by core-code** [yangshun1029/aria2gui#132]
Aria2GUI 1.4.1 claims to be version 1.4 (in the Finder and in the About Window)

the 'CFBundleShortVersionString' key in MacGap/Aria2GUI-Info.plist needs to be updated

**Comment by core-code** [comment]
is this going to be fixed for the next release?

**Comment by yangshun1029** [comment]
@core-code yep

**Comment by core-code** [comment]
thanks! ;)
