### ISSUE TITLE
Arial2GUI has error:internal server error

### ISSUE THREAD

**Issue by tomoro68** [yangshun1029/aria2gui#133]
i've met the following problem, when i open arial2GUI, always“Error：internal server error”
有人碰到类似问题吗？是arial2文件不对，还是需要更改哪些设置？还是最近DU爸爸封杀了？

<img width="791" alt="2018-08-06 9 51 53" src="https://user-images.githubusercontent.com/42145487/43721058-64da0e88-99c4-11e8-9ad9-90e284e96a79.png">

<img width="898" alt="2018-08-06 9 51 32" src="https://user-images.githubusercontent.com/42145487/43721071-6ae80280-99c4-11e8-8477-96331a540826.png">

我就是在这里下载的最新的arial2GUI：
i downloaded arial2GUI from here：
https://github.com/yangshun1029/aria2gui/releases

**Comment by eason0108** [comment]
samesame

**Comment by eXcellme** [comment]
same error

**Comment by eXcellme** [comment]
@eason0108 @tomoro68 mine became normal after I installed aria2...
