### ISSUE TITLE
无法实用移动硬盘下载

### ISSUE THREAD

**Issue by yuanfsc** [yangshun1029/aria2gui#134]
macbook air 本地硬盘下载没问题，接上seagate移动硬盘后，提示无法创建目录，是权限问题吗？我是管理员身份啊，怎么解决呢 谢谢

**Comment by yangshun1029** [comment]
是权限问题，你可以先在移动硬盘里面自己手动创建一个文件夹，然后在设置里面把默认下载路径设置成你创建的文件夹
