### ISSUE TITLE
如何修改最大连接线程数？

### ISSUE THREAD

**Issue by xuanxiaodeyu** [yangshun1029/aria2gui#135]
客户端设置中没有发现此选项

**Comment by trymesoft** [comment]
> 既然作者说了可以修改线程数，那么肯定在客户端的某处，而且这种使用的问题没必要提issue吧😂（逃）
- 点开左上角Aria2GUI，偏好设置
![image](https://user-images.githubusercontent.com/24319553/44251870-a37dee00-a22c-11e8-952e-53172d0fd61f.png)
- 网络选项里就可以更改了
![image](https://user-images.githubusercontent.com/24319553/44251891-bd1f3580-a22c-11e8-8235-315afba0fe24.png)
