### ISSUE TITLE
最近几天速度无法提上去

### ISSUE THREAD

**Issue by himrcs** [yangshun1029/aria2gui#137]
最近几天不论是连接宽带还是使用Wi-Fi，aria2 gui的速度不是很理想，基本稳定在100kB/s，不知道是不是百度升级了限制？特别希望作者能够作出软件的相应的升级。已经用作者的这个客户端很久了，如果可以的话，赞助也是没有问题的
![2018-09-17 11 10 20](https://user-images.githubusercontent.com/31501961/45604765-4911c080-ba6a-11e8-9c58-db5bef7da636.png)

**Comment by starlightjy** [comment]
我的也是很慢了
最近连接数都是1,没法多线程的话就没法加速了...

**Comment by baysonfox** [comment]
+1

**Comment by zzhzzhzzh** [comment]
+1

**Comment by vsp6688** [comment]
+1

**Comment by vsp6688** [comment]
+1 最近百度升级，以失效，作者也没写明，
如果急用可以去PANDONWLOAD管网下载最新版，已经更新WIN下面可用

**Comment by yangshun1029** [comment]
@himrcs 本软件只能决定aria2导出下载最大线程数，服务器能给你下载的线程数不是本应用能决定的
