### ISSUE TITLE
有计划增加状态栏图标的功能吗？

### ISSUE THREAD

**Issue by jackwish** [yangshun1029/aria2gui#14]
是否可以增加一个状态栏图标，点击图标呼出应用。同时可以隐藏 Dock 图标。
如果暂时没有的话我可以帮忙尝试一下~

**Comment by yangshun1029** [comment]
@jackwish 暂时没有这个计划，在弄设置，如果能帮忙的话那就太好了

**Comment by zhaojinxiang** [comment]
最好是，增加一个状态栏图标，隐藏 Dock 图标，开机启动

**Comment by jackwish** [comment]
方向转变没精力弄了…
