### ISSUE TITLE
导出下载键出现又消失

### ISSUE THREAD

**Issue by Mrhhhhhhx** [yangshun1029/aria2gui#140]
没有勾中文件准备下载时有导出下载选项，当点击文件之后，原本的导出下载选项却变成了一堆其他选项，当取消点击文件时，导出下载键消失

**Comment by zsirfs** [comment]
百度了做屏蔽。需要自己做一个元素检测去掉一些东西

**Comment by yangshun1029** [comment]
@Mrhhhhhhx 插件问题
