### ISSUE TITLE
新增下载提示错误，无法下载

### ISSUE THREAD

**Issue by AshtonCoop** [yangshun1029/aria2gui#15]
两三周前使用Aria2GUI没有任何问题，非常喜欢。
使用Mac系统。
这一两天发现新增百度下载后，任务立马从Active Tasks变成Other Tasks，并且后面有一个 x 符号。鼠标移动到那里提示：error HTTP response header was bad or unexpected
重新更新了百度盘插件以及重新安装最新版aria2gui发现还是如此。
请问这个问题如何解决？非常感谢！！

**Comment by yangshun1029** [comment]
尝试一下其他网盘插件是否可以使用，百度网盘插件已经挂了

**Comment by AshtonCoop** [comment]
好吧，改用迅雷离线了。感谢！

**Comment by AshtonCoop** [comment]
好吧，改用迅雷离线了。感谢！
