### ISSUE TITLE
使用经验分享

### ISSUE THREAD

**Issue by HaimmingYu** [yangshun1029/aria2gui#155]
使用经验分享
下载差不多 700MB 以上的文件 
必须 要打开百度云 然后 下载 试用 加速 

才能用aria2gui添加下载

**Comment by luoei** [comment]
真棒，之前速度1M得下载，使用您的方法，18M/s下载。

**Comment by MicroKibaco** [comment]
我的无法使用了

**Comment by HaimmingYu** [comment]
是不是升级系统了 最新的 好像不能用@MicroKibaco

**Comment by MicroKibaco** [comment]
升级系统,你说的是Google浏览器还是Mac系统

**Comment by HaimmingYu** [comment]
mac系统
