### ISSUE TITLE
文件名总是出问题

### ISSUE THREAD

**Issue by yanyang1025** [yangshun1029/aria2gui#157]
Aria2GUI, 1.4.1, Mac OS Mojave 10.14.2

下载的文件名从某天开始突然变成只剩文件格式后缀，文件名消失了；或者没有后缀只剩下一段数字或字母的文件名；有时候甚至格式后缀也只剩一部分，比如.mp4 保存下来的文件只剩下 p4作为文件名，不知道可以怎么解决呢？感谢开发者！

**Comment by JJ7539** [comment]
我也突然遇到这样的问题！！！

**Comment by yangshun1029** [comment]
@yanyang1025 @JJ7539 参考https://github.com/acgotaku/BaiduExporter/issues/638

**Comment by yanyang1025** [comment]
> @yanyang1025 @JJ7539 插件问题，详见[acgotaku/BaiduExporter#638](https://github.com/acgotaku/BaiduExporter/issues/638)

感谢！耐心等待修复中……
