### ISSUE TITLE
Dock栏图标上的速度不会动

### ISSUE THREAD

**Issue by xiebruce** [yangshun1029/aria2gui#160]
如图，Dock栏图标的速度不会动，按道理来说应该是会动的吧？因为如果不会动的话，标这个速度有什么用呢？难道是四舍五入？实际速度是1.6几M/s，就直接四舍五入成2M/s？
![image](https://user-images.githubusercontent.com/13575500/53801082-30925580-3f79-11e9-92ed-4c2fdab8dd1d.png)

**Comment by yangshun1029** [comment]
这个数值是webui里面下载速度的取整，减少自动刷新时间可以提高刷新速度

**Comment by xiebruce** [comment]
@yangshun1029 哦，怪不得，下载速度一直是1.5几到1.6几之间，所以取整就是2一直不变，其实我感觉应该可以字体弄小点，搞个两位数甚至3位数吧？把MB的B去掉，就用K或M大家也能看明白
