### ISSUE TITLE
希望作者继续更新软件,chrome扩展下载文件名问题解决

### ISSUE THREAD

**Issue by zwb124** [yangshun1029/aria2gui#162]
之前一直用这个，后来换了一下motrix，但是motrix没有aria2gui稳定，下载百度网盘文件经常下着下着就自己停了，还没发恢复下载，不得已只能继续用aria2gui了，希望作者继续努力啊，支持支持。另外motrix修改的百度网盘的扩展是没问题的，建议作者参考一下

**Comment by yangshun1029** [comment]
@zwb124  motrix挺好用的，当然这个aria2gui也会继续更新，但是没有确定的时间
