### ISSUE TITLE
添加任务弹出层中的链接地址输入框无法粘贴

### ISSUE THREAD

**Issue by suclogger** [yangshun1029/aria2gui#2]
如题。
录入是可以的，但是无法粘贴链接地址。

**Comment by yaoxinghuo** [comment]
是因为菜单里没有Edit-Copy Pase哪些，所以不能用CMD+C CMD+V，只能用邮件里的粘贴，希望增加Edit编辑菜单

**Comment by yangshun1029** [comment]
确实是如此，已经添加了edit，可以复制粘贴了，请下载最新版本

**Comment by suclogger** [comment]
完美!
