### ISSUE TITLE
浏览器识别不出最新版1.2.5aria2gui

### ISSUE THREAD

**Issue by Melonss** [yangshun1029/aria2gui#21]
最新版aria2gui貌似浏览器百度云插件识别不出，提示是否开启了aria2gui

**Comment by yangshun1029** [comment]
这里正常呢，用的什么浏览器，是safari吗？ @Melonss

**Comment by Melonss** [comment]
@yangshun1029 safari和chrome都试过，提示没打开aria2gui

**Comment by Melonss** [comment]
@yangshun1029 换回老版本后就又好了

**Comment by maijunxuan** [comment]
@yangshun1029 你好，新版和旧版chrome游览器都不能识别。

**Comment by yangshun1029** [comment]
CMM删除应用重新安装试试，或者在设置里面重置下配置文件，一般都能解决
