### ISSUE TITLE
使用 Aria2 WebUI

### ISSUE THREAD

**Issue by wangmeng1995** [yangshun1029/aria2gui#22]
可否考虑同时提供 Aria2 WebUI 作为控制界面，个人更喜欢。
![image](https://cloud.githubusercontent.com/assets/20497596/17123284/1118ab30-5315-11e6-8102-df3dd8958ccb.png)
这里简单替换了一下文件。

**Comment by yangshun1029** [comment]
@wangmeng1995 可以的，等待更新

**Comment by yangshun1029** [comment]
@wangmeng1995 可以的，等待更新

**Comment by yangshun1029** [comment]
@wangmeng1995 可以的，等待更新

**Comment by mildnes** [comment]
这个我自己替换了。但是替换之后貌似连接出错了。
