### ISSUE TITLE
能否增加语音选项 可添加中文

### ISSUE THREAD

**Issue by Evan-Mac** [yangshun1029/aria2gui#23]
希望添加语音选项 添加中文 英文 可自定义

**Comment by yangshun1029** [comment]
@Evan-Mac 语言选项？因为YAAW原版UI就是英文，没有中文的，而且就那几个单词，使用上没多大障碍，你可以下个汉化版自行替换，或者可以等下次更新，会发两个版本，另外一个版本可以选择语言。
