### ISSUE TITLE
提示无法创建目录

### ISSUE THREAD

**Issue by evolot** [yangshun1029/aria2gui#25]
10.11.2 chrome 安装百度网盘助手插件和aria2gui
安装好之后百度网盘导出到aria2 rpc ，aria2gui能显示任务 但是几秒之后other tasks显示 error aria2 could not create directory 偏好设置修改配置文件把--dir="$HOME/Downloads/"改成--dir="/Users/dear/Downloads/"之后重启aria2 gui显示红色提示error internal server error 此时网盘使用导出到aria2 rpc插件提示"下载失败!是不是没有开启aria2"

**Comment by evolot** [comment]
换IP 192和127都不行 没办法用cleanmymac卸载了然后安装老版本 啥都没改莫名其妙的就好了 真的是满速下载 50M跑到6M/S

**Comment by ViggoZ** [comment]
error aria2 could not create directory.一直没解决

**Comment by Radar-Lei** [comment]
同问

**Comment by DuaneDuan** [comment]
这个问题我遇到过，我是因为运行aria2c的用户无法在下载的路径创建文件，所以改运行用户为root后就没有问题。
