### ISSUE TITLE
下载后，不小心打开了aria2gui 。之后拖进应用程序就报错。

### ISSUE THREAD

**Issue by lhuanyun** [yangshun1029/aria2gui#26]
下载后，直接运行了aria2gui ，发现可以正常使用了很开心
再把aria2gui 放进应用程序，一打开就出现Internal server error报错。
应该是第一次运行生成了配置文件，指向了下载后运行aria2所在的文件夹路径
--------------
那么要怎么修改回来呢。感谢大哥，抽空帮个忙

**Comment by lhuanyun** [comment]
我用cleanmymac 卸载了一次 aria2gui 重新下载放进应用程序里面打开，这样就正常了

**Comment by yangshun1029** [comment]
@lhuanyun 可以在设置里面重置下配置文件就可以了

**Comment by yangshun1029** [comment]
新版已经解决路径问题
