### ISSUE TITLE
请问如何将aria2gui的下载路径改成移动硬盘

### ISSUE THREAD

**Issue by Iasnate** [yangshun1029/aria2gui#27]
编辑了startaria.sh  将下载路径改为dir=“/Volumes/HDD2“之后发现无法下载 添加任务就报错 请问应该如何修改呢  外接移动硬盘名字是HDD2,谢谢。

**Comment by yangshun1029** [comment]
@Iasnate 我在外置硬盘上面试了下，确实是这样，aria2无法创建文件所以报错，应该是权限问题，我想想怎么解决

**Comment by PhysiX2011** [comment]
@yangshun1029 "在网页插件里面设置下载路径/Volumes/HDD2" 这句话是什么意思？什么插件？aria2gui里面的setting是不能修改路径的

**Comment by yangshun1029** [comment]
@PhysiX2011 我指的是浏览器的导出插件，已百度网盘为例，https://github.com/acgotaku/BaiduExporter就是这个插件，在百度网盘页面有个导出按钮，里面有个设置的选项，可以自己定义下载路径。

**Comment by PhysiX2011** [comment]
@yangshun1029 屌啊，可以啦，十分感谢！

**Comment by tdyso** [comment]
请问怎么找StartAria2c.sh这个文件呀，路径在哪？

**Comment by yangshun1029** [comment]
@tdyso ~/Library/Application Support/com.Aria2GUI/sh/

**Comment by clotong** [comment]
1.2.8为何在StartAria2c.sh修改后，打开aria2gui配置文件又变回Downloads了

**Comment by clotong** [comment]
1.2.8为何在StartAria2c.sh中修改下载路径后，打开aria2gui后配置文件的下载路径又变回Downloads了

**Comment by yangshun1029** [comment]
@clotong 默认不能修改了，避免因为权限问题报错，可以在插件里面可以自己定义下载路径的，这样不会报错

**Comment by oufumihiko** [comment]
@yangshun1029 我在路由器上的aria2的和mac上的下载路径不同怎么破，总不能下一次改一次插件吧？

**Comment by yangshun1029** [comment]
@oufumihiko 目前只能这样
