### ISSUE TITLE
Error: Internal server error

### ISSUE THREAD

**Issue by tigerZhang86** [yangshun1029/aria2gui#28]
安装后，运行Aria2GUI.app，提示“Error: Internal server error”，不知道是什么原因。
需要额外配置或者需要其他服务支持吗？
Aria2GUI-v1.2.5.zip

**Comment by yangshun1029** [comment]
设置里面重置下配置文件试试

**Comment by tigerZhang86** [comment]
JSON-RPC Path 需要把“http://localhost:6800/jsonrpc”改为“http://127.0.0.1:6800/jsonrpc”
会不会和我修改了hosts有关系。
