### ISSUE TITLE
无法单独更新aria2

### ISSUE THREAD

**Issue by ansonfish** [yangshun1029/aria2gui#29]
以前的版本，可以单独更新aria2（即aria2c），但现在好像不行了。

**Comment by ansonfish** [comment]
我把aria2的1.26版本改名替换resource目录里的aria2gui，报错。

**Comment by yangshun1029** [comment]
@ansonfish 应该是可以的，不知道报错的原因，等新版更新吧

**Comment by yangshun1029** [comment]
是1.26某个版本的坑，新版本已经修复
