### ISSUE TITLE
10.11.6 百度网盘 没有出现导入aria2.。。 是我不会用，还是不兼容呢。

### ISSUE THREAD

**Issue by lhuanyun** [yangshun1029/aria2gui#30]
谢谢大大的工具 很好用，感觉每次都要拷贝地址到aria2gui 去下载有点累。。。能不能兼容 10.11.6

**Comment by yangshun1029** [comment]
@lhuanyun 浏览器是safari还是chrome呢

**Comment by lhuanyun** [comment]
safari

**Comment by yangshun1029** [comment]
@lhuanyun 那是safari导出插件的问题，去https://github.com/acgotaku/BaiduExporter/issues提问看看

**Comment by lhuanyun** [comment]
似乎safari兼容插件没有更新...

**Comment by yangshun1029** [comment]
@lhuanyun 之前作者说过原因了，因为safari对于扩展有诸多限制，有些功能实现不了很正常的，除非苹果开放这些api，否则开发者也无能为力。

**Comment by lhuanyun** [comment]
crying..... 我现在都要先用 safari 下载，然后拷贝地址到 aria2gui去， 下载完后要去“下载文件夹”删除用safari下载的临时文件。 感觉这样好烦恼
