### ISSUE TITLE
感觉新版的顶部是黑色没有原来的漂亮

### ISSUE THREAD

**Issue by ykqmain** [yangshun1029/aria2gui#32]
可以设置吗

**Comment by yangshun1029** [comment]
@ykqmain 10.12好像是这样的，我升级后再想办法解决，不是设置问题，框架跟新版系统有些不兼容吧

**Comment by thescfai** [comment]
期待作者更新哇，另外为什么百度盘导出插件在百度盘改版后加载特别慢呢？

**Comment by ykqmain** [comment]
@thescfai  因为百度限速了，貌似最高1M/s

**Comment by ykqmain** [comment]
@yangshun1029 
哥们，注意身体，大晚上的别折腾早点睡。
病人深知健康才是本钱

**Comment by yangshun1029** [comment]
@ykqmain 好的，推完就睡了
