### ISSUE TITLE
请教新版百度云怎么报错啊

### ISSUE THREAD

**Issue by songxing10000** [yangshun1029/aria2gui#33]
个人操作步骤
下Aria2软件放到应用程序里，下载chrome插件用于检测百度云里的下载地址。然后打开Aria2
提示internel server error

求解决方案

**Comment by yangshun1029** [comment]
@songxing10000 这种问题我这里是不能重现的，只能先自查一下，首先更新插件到最新版，看下进程里面有没有两个aria2gui进程，另外提示internel server error有时候并不是因为程序有任何问题，如果下载正常可以忽略这个提示。

**Comment by songxing10000** [comment]
@yangshun1029 之前有篇文章，是命令行安装aria2的，然后手动配置aria2.conf，不知道是不是因为这个原因引起，软件出错，或者是因为新版本的百度云，限制了aria2跟踪，，有没有针对腾讯云下载加速的啊，
