### ISSUE TITLE
一直提示没有打开aria2gui，无法下载

### ISSUE THREAD

**Issue by DarinJi** [yangshun1029/aria2gui#36]
卸载重装，换了几个版本的都不行。。求助

**Comment by AquaHacker** [comment]
截图看看；最好是先安装 Aria2 核心程序（在https://aria2.github.io）
如果你是 Mac （就安装 1.27.1 版本的）其他平台不负责；
## 另外也是特别重要的是
需要配合 谷歌浏览器插件（在https://github.com/acgotaku/BaiduExporter ）
然后运行 Aria2GUI（我用的是这个https://github.com/yangshun1029/aria2gui） 
这样操作下来 不会有问题的。祝你好运！

**Comment by yangshun1029** [comment]
@AquaHacker aria2gui已经包含了aria2核心程序

**Comment by DarinJi** [comment]
是不是因为百度抽风了

**Comment by fanhefan** [comment]
之前用的很爽 最近不能用了 看了下 百度云的界面改了 是不是因为改版的原因

**Comment by DarinJi** [comment]
折腾死了，还是没有弄好，有没有大神帮忙解决下啊

**Comment by sanen2** [comment]
是不是你没先打开软件？

**Comment by AquaHacker** [comment]
托大神的福 自己做了汉化    需要的朋友可以找我要；另外很乐意贡献出来，不知道yangshun1029大神怎么看。
