### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by AletOne** [yangshun1029/aria2gui#38]
我用了proxifier，但是打开aria就没有网络连接。aria的配置文件里没有写代理，应该走的proxifier设置的代理吧？可是一直都是internal server error

**Comment by sanen2** [comment]
没用proxifier的我一样也显示这个。1.2.9版本

**Comment by yangshun1029** [comment]
代理问题见https://github.com/yangshun1029/aria2gui/issues/7
