### ISSUE TITLE
gui的改进

### ISSUE THREAD

**Issue by vokins** [yangshun1029/aria2gui#45]
在威锋论坛看到了这个帖子

http://bbs.feng.com/forum.php?mod=viewthread&tid=11000917&extra=page%3D1

感觉挺有意思的，不知道有没有时间改进下？

ps。其实我觉得在打开的界面，添加那一行工具栏下方能否直接留一行位置，直接输入link地址。

**Comment by yangshun1029** [comment]
@vokins 不知道你所说的改进是什么，你发的这个只是在把aria2gui换了一个Aria2Ng的webui而已，可能你说的改进的功能就是内置了那个百度网盘的页面和那个没有什么意义的测试，这些不符合我的设计初衷，所以以后也不会涉及，如果你喜欢这种可自行替换并编译
