### ISSUE TITLE
能否添加日语本地化？

### ISSUE THREAD

**Issue by hououinkami** [yangshun1029/aria2gui#46]
用的日文系统，强迫症想要日语本地化，能否添加呢？如果可以的话我可以帮忙翻译，谢谢！

**Comment by yangshun1029** [comment]
@hououinkami 可以的，我会添加一个日语的Localizable Strings，你对照着翻译，webui的翻译可以参考汉化的方式

**Comment by yangshun1029** [comment]
@hououinkami 留一个邮箱，我把需要翻译的项目发给你

**Comment by hououinkami** [comment]
@yangshun1029 hououinkami@yahoo.co.jp
麻烦发我邮箱吧

**Comment by yangshun1029** [comment]
@hououinkami 你的邮箱我记下了，等偏好设置都加了以后再一起发

**Comment by lm2343635** [comment]
我来做吧，顺便想把Bootstrap版本升级一下！
