### ISSUE TITLE
ftp无法下载？

### ISSUE THREAD

**Issue by mengzhihoing** [yangshun1029/aria2gui#49]
ftp://ygdy8:ygdy8@y219.dydytt.net:8220/[阳光电影www.ygdy8.com].三少爷的剑.HD.720p.国语中字.mkv

上面这个链接貌似无法下载？大家有同样情况的吗？

**Comment by yangshun1029** [comment]
这种地址建议你用迅雷离线下载，不是前面有个ftp://就是可以下载的ftp文件
