### ISSUE TITLE
aria2gui 在退出后不能保存下载的记录

### ISSUE THREAD

**Issue by zhen-ke** [yangshun1029/aria2gui#5]
经过搜索查了相关的命令后发现，在startaria.sh里添加force-save=true的命令后，就可以实现退出后不能保存下载的记录的问题，但又出现个新问题，重新打开aria2gui ，下载后的记录进度加载非常慢，不知道是不是aria2自身的原因

**Comment by chen2319** [comment]
同样，再打开后，原来的进度都归0了， 如何解决？startaria.sh在哪配置？我理解这个应该是默认配置好的。

**Comment by yangshun1029** [comment]
@chen2319 https://aria2.github.io/manual/en/html/aria2c.html?highlight=force%20save#cmdoption--force-save 这个选项不是那么想的那样保存下载记录用的，开启后是会保存你所有下载过的任务，但是你删除了一些你下载过的文件，那么再下次开aria2gui后全部自动下载，在MAC上你是不会想看到这样状况的，如果真有这个需要，在设置里面打开配置文件自己添加
