### ISSUE TITLE
用了一会儿 下载速度就降到100KiB/s 求助

### ISSUE THREAD

**Issue by Yogurtliker** [yangshun1029/aria2gui#56]
Chrome插件 Aria2gui都运转正常 为什么下载速度又慢下来了。。。还是和云盘资源有关？

**Comment by Yogurtliker** [comment]
![2017-03-01 22 44 16](https://cloud.githubusercontent.com/assets/26077335/23464872/851afea8-fed1-11e6-8ce2-46d797dfb2e7.jpg)
![2017-03-01 22 44 53](https://cloud.githubusercontent.com/assets/26077335/23464935/ae7fa9ce-fed1-11e6-838b-e3a5677cf813.jpg)

**Comment by yangshun1029** [comment]
百度网盘限速了，跟客户端无关
