### ISSUE TITLE
多任务下载文件丢失

### ISSUE THREAD

**Issue by leo493852107** [yangshun1029/aria2gui#6]
大神你好，根据http://bbs.feng.com/read-htm-tid-9585996.html文章和aria2gui操作。
使用的时候有几个问题：
1.百度云同时下载多个文件夹下的多个视频，每个文件夹下面会丢失1-2个视频
2.完成时候，悬浮窗口一定几率关不掉（不知是否跟多线程有关）
本人小白，求教

**Comment by yangshun1029** [comment]
你给出的链接里面的使用方法跟这个应用没有什么关系，这些问题不能重现所以也找不到对应的解决方法
