### ISSUE TITLE
升级1.3(6)下载速度波动，间歇暂停问题

### ISSUE THREAD

**Issue by xuehao** [yangshun1029/aria2gui#67]
下载速度从最高降到0，暂停，再从0升到最高，循环往复。
不知道是软件Bug还是百度云问题。

**Comment by MoreSunShine** [comment]
我的也出现了这样的问题。最近刚发生的状况，之前都是都稳定得慢速下载。

**Comment by nl101531** [comment]
这个貌似和账户有关系,我换个账户速度没问题了.可能加了黑名单功能了吧

**Comment by ZoranWang** [comment]
版本1.3(8)也出现这个问题
