### ISSUE TITLE
A critical bug!!! Aria2.log无限增大

### ISSUE THREAD

**Issue by techlarry** [yangshun1029/aria2gui#68]
aria2.log文件  无限增大。

我的那个文件都有7GB了，磁盘空间都小了很多。

/Application/Aria2GUI.app/Contents/Rescoures/aria2.log文件

**Comment by techlarry** [comment]
删了就好了，但最好设置一个上线。

**Comment by leenchan** [comment]
建议配置都写在 conf，这样好配置，例如自己在conf里面 取消log，其实大多数人都不看log的

**Comment by yangshun1029** [comment]
@leenchan 把配置都写在conf里有些功能无法实现，下个版本会在设置里面加个打开Log记录的按钮，默认不开启

**Comment by black-snowflake** [comment]
下载路径带空格，YAAW无法识别到完整路径

**Comment by sunrisewestern** [comment]
哈哈我攒了18G，可怜我128的mac
