### ISSUE TITLE
没有proxy settings

### ISSUE THREAD

**Issue by crazygao** [yangshun1029/aria2gui#7]
希望可以有 aria proxy 的设定， thanks

**Comment by yangshun1029** [comment]
不会涉及这个功能，aria2本身是支持proxy的，可以在启动命令里面添加

**Comment by yeasy** [comment]
同样希望添加这个功能。
有时候偶尔指定某个下载用代理，通过配置文件修改比较麻烦。

**Comment by lockfan** [comment]
/Applications/Aria2GUI.app/Contents/Resources/aria2.conf

加一行http-proxy=http://your_local_proxy:8080   不就好了

socket也可以支持

**Comment by vokins** [comment]
希望增加一个gui界面，thx
