### ISSUE TITLE
Can you please translate your app to English?

### ISSUE THREAD

**Issue by Metamba** [yangshun1029/aria2gui#72]
Hi.
It will be lovely to have an English version of your app? Can you please translate it to English?
Thanks for the great work.

**Comment by Metamba** [comment]
你好。
有一个英文版的应用程序会很可爱吗？ 你可以把它翻译成英文吗？
感谢您做的伟大工作。

**Comment by cuichacha** [comment]
@Metamba There is an English version. I am using the English version.

**Comment by Metamba** [comment]
@cuichacha Thanks. Just downloaded it.
