### ISSUE TITLE
提示Aria2 RPC 服务器错误

### ISSUE THREAD

**Issue by dongqw** [yangshun1029/aria2gui#8]
打开后提示：错误: Aria2 RPC 服务器错误
修改JSON-RPC Path和重启均无效

**Comment by yangshun1029** [comment]
先看下进程里面有没有aria2c，再检测下ip对不对，localhost换成127.0.0.1试试

**Comment by Yuzeyang** [comment]
我的也不行。。有没有别的办法？

**Comment by dongqw** [comment]
重启可以正常使用，但过一段时间又会不正常。改成127.0.0.1不会报错，但是Safari不能用百度盘插件添加任务，chrome可以添加。

**Comment by yangshun1029** [comment]
@dongqw 下载完成后有时候会显示aria2错误，web端报错，其实没有什么问题，再添加其他下载都是可以的。
