### ISSUE TITLE
满速下载导致的电脑死机

### ISSUE THREAD

**Issue by LichFaker** [yangshun1029/aria2gui#80]
Hi， 我使用aria2gui 最新 + 百度会员 长时间满速下载文件会导致网络卡死电脑无法正常关机的问题。
现象描述：
1. 浏览器无法正常退出， 强制退出后无法启动，且页面仍然显示，无法关掉
2. 其他应用还可以正常点击查看， 但无法打开网络， 鼠标停留在wifi图标前一直风火轮
3. 最近一次出现该问题的操作： 在原先12m/s下载时，点击设置中的限速，保存后直接崩溃。

mac 系统版本： 10.12.4

有人遇到过类似的问题吗？

**Comment by normalhh** [comment]
非会员，好像没有满速下载的时候。

**Comment by LichFaker** [comment]
@normalhh  买个百度超级会员就有了， 现在百度是根据ip限速的， 下载的时候经常不超过50k，太慢了
