### ISSUE TITLE
能否帮忙升级内置aria2版本？

### ISSUE THREAD

**Issue by ansonfish** [yangshun1029/aria2gui#9]
多谢了。

**Comment by yangshun1029** [comment]
下个版本会升级的

**Comment by zhen-ke** [comment]
@yangshun1029  自己在 aria2 的官网下载了 aria2c 文件的最新 1.21 版，并放到了 aria2GUI 的相应目录后，发现能成功升级内置的版本 ^_^

**Comment by ansonfish** [comment]
麻烦问一下，aria2GUI 的相应目录在哪里？找了很久也没找到。谢谢。

**Comment by yangshun1029** [comment]
@ansonfish /Applications/Aria2GUI.app/Contents/Resources/
