### ISSUE TITLE
“导出下载”消失了，不能使用了

### ISSUE THREAD

**Issue by kangzhi2016** [yangshun1029/aria2gui#91]
今天刚下载的这个，Mac，chrome，只是提示“初始化成功！”，单文件页面没有“导出下载”，多文件需要选中的情况下，不选中文件时有“导出下载”，选中文件之后“导出下载”就消失了。

**Comment by geekspeng** [comment]
更新网盘助手

**Comment by kangzhi2016** [comment]
非常感谢，已解决！
