### ISSUE TITLE
El Capitan 上使用 1.4 版本限速下载导致网络组件卡死

### ISSUE THREAD

**Issue by scatoday** [yangshun1029/aria2gui#96]
系统：OS X El Capitan 10.11.6，安装了最新的安全性更新
软件版本：aria2gui 1.4
晚上用aria2gui下载网盘导出的文件，后通过 UI 前端右上角的［ Settings］ 设置［Download Limit］为“ 1mb” 的限速，大概5～6分钟后电脑关闭显示器了（节能器里我设置了☑️5分钟后关闭显示器；☑️显示器关闭后，防止电脑自动进入睡眠），mac系统的网络组件就卡死了；试了两次，两次都是限速，网络组件都卡死了，没有测试无限速的情况。
后下载 1.3.8 版本使用，能够正常使用。

**Comment by Lnybb** [comment]
遇到类似的问题。macOS High Sierra 10.13.1，出现 SystemUIService 无响应的情况。

**Comment by KINGAhab** [comment]
一样问题，开始下载后提示internal server error 然后Mac卡死，只能强制重启，并且 SystemUIService 无响应。

**Comment by yangshun1029** [comment]
@scatoday @Lnybb @KINGAhab 应该是类似的情况，具体见https://github.com/yangshun1029/aria2gui/issues/100
