### ISSUE TITLE
显示“error aria2 could not create directory”

### ISSUE THREAD

**Issue by TomLiu2016** [yangshun1029/aria2gui#98]
不管下载什么都有这个问题，是我哪里配置不对吗？
截图如下

**Comment by yangshun1029** [comment]
@TomLiu2016  截图打不开

**Comment by TomLiu2016** [comment]
抱歉不是很经常上github……没注意消息

<img width="900" alt="aria2_error" src="https://user-images.githubusercontent.com/20353163/34000087-3fd95658-e127-11e7-99f6-7f7e1c6c251c.png">

**Comment by TomLiu2016** [comment]
@yangshun1029 请问这个问题解决了吗？看了其他人好像都没遇到跟我一样的问题，是不是我哪里没有设置好？

**Comment by yangshun1029** [comment]
@TomLiu2016 是不是修改过默认存储路径，遇到这个问题可以完全卸载（用CMM之类的软件）后重装应用试试

**Comment by TomLiu2016** [comment]
@yangshun1029 问题依然存在。没有修改过默认存储路径，刚刚重新安装了一遍，仍然没有解决。
![image](https://user-images.githubusercontent.com/20353163/34473818-5018cbe0-efb2-11e7-83c4-69cc47cfd6dd.png)

**Comment by yangshun1029** [comment]
@TomLiu2016  aria2 could not create directory 大多数是存储路径问题，看看你网盘导出插件里面有没有设置过路径，导出插件是不是最新版本
