### ISSUE TITLE
打开aria2gui导致high sierra系统崩溃

### ISSUE THREAD

**Issue by Arthurwu24** [yangshun1029/aria2gui#99]
系统版本：Version 10.13.2 
电脑： Macbook pro 2014
aria2gui版本： Version 1.4

今天刚出现的这个问题，用aria2gui下载东西就会导致电脑完全崩溃，之前并不会。
用终端杀死进程都无法解决，只能是重启。

另一台电脑，macbook air 2015，同样的系统，没出现这个问题，

**Comment by yangshun1029** [comment]
@Arthurwu24  系统问题，无法重现，所以我也无能为力
